# number of controller replicas to deploy
replicas: 1

image:
  repository: ghcr.io/mrhachi/mongodb-controller
  pullPolicy: IfNotPresent

# resource requests and limits
resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi
