//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alphav1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoAdminSpec) DeepCopyInto(out *MongoAdminSpec) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoAdminSpec.
func (in *MongoAdminSpec) DeepCopy() *MongoAdminSpec {
	if in == nil {
		return nil
	}
	out := new(MongoAdminSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoRoleSpec) DeepCopyInto(out *MongoRoleSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoRoleSpec.
func (in *MongoRoleSpec) DeepCopy() *MongoRoleSpec {
	if in == nil {
		return nil
	}
	out := new(MongoRoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoUserSpec) DeepCopyInto(out *MongoUserSpec) {
	*out = *in
	out.SecretRef = in.SecretRef
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]MongoRoleSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoUserSpec.
func (in *MongoUserSpec) DeepCopy() *MongoUserSpec {
	if in == nil {
		return nil
	}
	out := new(MongoUserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SingleTenantMongoDB) DeepCopyInto(out *SingleTenantMongoDB) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SingleTenantMongoDB.
func (in *SingleTenantMongoDB) DeepCopy() *SingleTenantMongoDB {
	if in == nil {
		return nil
	}
	out := new(SingleTenantMongoDB)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SingleTenantMongoDB) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SingleTenantMongoDBList) DeepCopyInto(out *SingleTenantMongoDBList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SingleTenantMongoDB, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SingleTenantMongoDBList.
func (in *SingleTenantMongoDBList) DeepCopy() *SingleTenantMongoDBList {
	if in == nil {
		return nil
	}
	out := new(SingleTenantMongoDBList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SingleTenantMongoDBList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SingleTenantMongoDBSpec) DeepCopyInto(out *SingleTenantMongoDBSpec) {
	*out = *in
	out.Admin = in.Admin
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]MongoUserSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Storage = in.Storage
	out.Resources = in.Resources
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SingleTenantMongoDBSpec.
func (in *SingleTenantMongoDBSpec) DeepCopy() *SingleTenantMongoDBSpec {
	if in == nil {
		return nil
	}
	out := new(SingleTenantMongoDBSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SingleTenantMongoDBStatus) DeepCopyInto(out *SingleTenantMongoDBStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SingleTenantMongoDBStatus.
func (in *SingleTenantMongoDBStatus) DeepCopy() *SingleTenantMongoDBStatus {
	if in == nil {
		return nil
	}
	out := new(SingleTenantMongoDBStatus)
	in.DeepCopyInto(out)
	return out
}
