name: Chart Test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
    branches:
      - main
    paths:
      - charts/**

jobs:
  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v7 # v6.0.2
        with:
          persist-credentials: false

      - name: Install the latest version of Helm
        uses: azure/setup-helm@v5

      - name: Verify Helm installation
        run: helm version

      - name: Test mongodb-operator chart
        run: make chart-test
