name: Controller Tag

on:
  push:
    tags:
      - controller-*

permissions:
  packages: write

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Setup crane
        uses: imjasonh/setup-crane@v0.7

      - name: Extract version from tag and add as tag to image
        run: |
          VERSION="${TAG#controller-}"

          crane auth login ghcr.io -u "${ACTOR}" -p "${GITHUB_TOKEN}"
          crane cp \
            ghcr.io/${REPOSITORY_OWNER}/mongodb-controller:${COMMIT_HASH} \
            ghcr.io/${REPOSITORY_OWNER}/mongodb-controller:${VERSION}

          echo "Promoted ${COMMIT_HASH} -> ${VERSION}"
        env:
          TAG: "${{ github.ref_name }}"
          ACTOR: "${{ github.actor }}"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          COMMIT_HASH: "${{ github.sha }}"
          REPOSITORY_OWNER: "${{ github.repository_owner }}"
