name: Mongo DB Build and Scan

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
    branches:
      - main
    paths:
      - database/**

jobs:
  trivy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build
        uses: docker/build-push-action@v7
        with:
          context: database
          tags: mongodb:ci
          load: true
          push: false

      - name: Run Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: mongodb:ci
          severity: HIGH,CRITICAL
          format: table
          exit-code: 1
