name: MongoDB Push

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - database/**

permissions:
  contents: read
  packages: write

jobs:
  push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - name: Repository owner name to lowercase
        id: preprocessing
        env:
          GITHUB_REPOSITORY_OWNER: "${{ github.repository_owner }}"
        run: |
          echo "owner=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT
          echo "Repository owner (lowercase): ${GITHUB_REPOSITORY_OWNER,,}"

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build
        uses: docker/build-push-action@v7
        with:
          context: database
          tags: ghcr.io/${{ steps.preprocessing.outputs.owner }}/mongodb:${{ github.sha }}
          push: true
